---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: local-issuer
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-cert-manager
  interval: 1m0s
  path: azure/tmc-sm/base/local-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-configs
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: local-issuer
