---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tmc-ldap-overlay
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tmc-install
  interval: 1m0s
  path: azure/tmc-sm/base/ldap-overlay
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-configs
    namespace: tanzu-continuousdelivery-resources
