---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tmc-repo
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-external-dns
  images:
  - name: harbor.mpmtmclab.io/tmc/package-repository
    newName: harbor.mpmtmclab.io/tmc/package-repository
    newTag: 1.0.0
  interval: 1m0s
  path: azure/tmc-sm/base/tmc-repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-configs
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: packaging.carvel.dev/v1alpha1
      kind: PackageRepository
      name: tanzu-mission-control-packages
      namespace: tmc-local
