---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: grafana
  namespace: packages
spec:
  serviceAccountName: tkgm-gitops-sa
  packageRef:
    refName: grafana.tanzu.vmware.com
    versionSelection:
      constraints: 7.5.16+vmware.1-tkg.1
