---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./overlays/workload 
  prune: true
  sourceRef:
    kind: GitRepository
    name: tkgm-gitops
    namespace: tanzu-continuousdelivery-resources
