---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages
spec:
  interval: 1m0s
  path: ./flux-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: tkgm-gitops
