{{- if eq .Values.autoscaling.enabled true }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler-management
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  - machines
  - machinesets
  verbs:
  - get
  - list
  - update
  - watch
  - patch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments/scale
  - machinesets/scale
  verbs:
  - get
  - update
{{- end }}
