{{- if eq .Values.autoscaling.enabled true }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.cluster_name }}-autoscaler-workload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler-workload
subjects:
- kind: ServiceAccount
  name: {{ .Values.cluster_name }}-autoscaler
  namespace: {{ .Values.cluster_namespace }}
{{- end }}
