---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: addons-management/core-package-repo
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-core-package-repository
  namespace: {{ .Values.cluster_namespace }}
spec:
  clusterSelector:
    matchLabels:
      tkg.tanzu.vmware.com/cluster-name: {{ .Values.cluster_name }}
  resources:
  - kind: Secret
    name: {{ .Values.cluster_name }}-core-package-repository-crs
  strategy: ApplyOnce
