---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: metrics/metrics-server
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    tkg.tanzu.vmware.com/addon-name: metrics-server
    tkg.tanzu.vmware.com/cluster-name: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-metrics-server-addon
  namespace: {{ .Values.cluster_namespace }}
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    metricsServer:
      namespace: kube-system
      config:
        args: []
        probe:
          failureThreshold: 3
          periodSeconds: 10
        apiServiceInsecureTLS: true
      image:
        name: metrics-server
        tag: v0.6.1_vmware.1
        repository: {{ .Values.imageRepository }}
        pullPolicy: IfNotPresent
type: tkg.tanzu.vmware.com/addon
