---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: addons-management/kapp-controller
    tkg.tanzu.vmware.com/remote-app: "true"
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    tkg.tanzu.vmware.com/addon-name: kapp-controller
    tkg.tanzu.vmware.com/cluster-name: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-kapp-controller-addon
  namespace: {{ .Values.cluster_namespace }}
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    kappController:
      namespace: tkg-system
      createNamespace: true
      globalNamespace: tanzu-package-repo-global
      image:
        repository: {{ .Values.imageRepository }}
        path: kapp-controller
        tag: v0.38.4_vmware.1
        pullPolicy: IfNotPresent
      deployment:
        concurrency: 4
        coreDNSIP: 100.64.0.10
        hostNetwork: true
        priorityClassName: system-cluster-critical
        apiPort: 10100
        metricsBindAddress: "0"
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
      config: {}
type: tkg.tanzu.vmware.com/addon
