---
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    tkg.tanzu.vmware.com/cluster-name: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-config-values
  namespace: {{ .Values.cluster_namespace }}
stringData:
  value: |
    CLUSTER_NAME: {{ .Values.cluster_name }}
    CLUSTER_PLAN: {{ .Values.cluster_plan }}
    NAMESPACE: {{ .Values.cluster_namespace }}
    INFRASTRUCTURE_PROVIDER: vsphere
    IS_WINDOWS_WORKLOAD_CLUSTER: false
    SIZE: null
    CONTROLPLANE_SIZE: null
    WORKER_SIZE: null
    ENABLE_CEIP_PARTICIPATION: false
    DEPLOY_TKG_ON_VSPHERE7: true
    ENABLE_TKGS_ON_VSPHERE7: null
    VSPHERE_NUM_CPUS: 2
    VSPHERE_DISK_GIB: 40
    VSPHERE_MEM_MIB: 4096
    VSPHERE_CONTROL_PLANE_NUM_CPUS: {{ .Values.control_plane.numCPUs }}
    VSPHERE_CONTROL_PLANE_DISK_GIB: {{ .Values.control_plane.diskGiB }}
    VSPHERE_CONTROL_PLANE_MEM_MIB: {{ .Values.control_plane.memoryMiB }}
    VSPHERE_WORKER_NUM_CPUS: {{ .Values.worker.numCPUs }}
    VSPHERE_WORKER_DISK_GIB: {{ .Values.worker.diskGiB }}
    VSPHERE_WORKER_MEM_MIB: {{ .Values.worker.memoryMiB }}
    VSPHERE_CLONE_MODE: fullClone
    VSPHERE_NETWORK: {{ .Values.vsphere.networkName }}
    VSPHERE_TEMPLATE: {{ .Values.vsphere.template }}
    VIP_NETWORK_INTERFACE: eth0
    VSPHERE_SSH_AUTHORIZED_KEY: {{ .Values.vsphere.ssh_public_key }}
    VSPHERE_USERNAME: {{ .Values.vsphere.username }}
    VSPHERE_REGION: null
    VSPHERE_ZONE: null
    VSPHERE_SERVER: {{ .Values.vsphere.server }}
    VSPHERE_DATACENTER: {{ .Values.vsphere.datacenter }}
    VSPHERE_RESOURCE_POOL: {{ .Values.vsphere.resourcePool }}
    VSPHERE_DATASTORE: {{ .Values.vsphere.datastore }}
    VSPHERE_FOLDER: {{ .Values.vsphere.folder }}
    VSPHERE_STORAGE_POLICY_ID: ""
    VSPHERE_TLS_THUMBPRINT: ""
    VSPHERE_INSECURE: true
    VSPHERE_CONTROL_PLANE_ENDPOINT: ""
    VSPHERE_CONTROL_PLANE_ENDPOINT_PORT: 6443
    NSXT_POD_ROUTING_ENABLED: false
    NSXT_ROUTER_PATH: ""
    NSXT_USERNAME: ""
    NSXT_MANAGER_HOST: ""
    NSXT_ALLOW_UNVERIFIED_SSL: "false"
    NSXT_REMOTE_AUTH: "false"
    NSXT_VMC_ACCESS_TOKEN: ""
    NSXT_VMC_AUTH_HOST: ""
    NSXT_CLIENT_CERT_KEY_DATA: ""
    NSXT_CLIENT_CERT_DATA: ""
    NSXT_ROOT_CA_DATA_B64: ""
    NSXT_SECRET_NAME: cloud-provider-vsphere-nsxt-credentials
    NSXT_SECRET_NAMESPACE: kube-system
    ENABLE_OIDC: false
    OIDC_ISSUER_URL: null
    OIDC_USERNAME_CLAIM: null
    OIDC_GROUPS_CLAIM: null
    OIDC_DEX_CA: null
    ENABLE_MHC: true
    ENABLE_MHC_WORKER_NODE: true
    ENABLE_MHC_CONTROL_PLANE: true
    MHC_UNKNOWN_STATUS_TIMEOUT: 5m
    MHC_FALSE_STATUS_TIMEOUT: 12m
    TKG_CUSTOM_IMAGE_REPOSITORY: ""
    TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY: false
    TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE: ""
    TKG_HTTP_PROXY: ""
    TKG_HTTPS_PROXY: ""
    TKG_NO_PROXY: ""
    TKG_PROXY_CA_CERT: ""
    TKG_IP_FAMILY: null
    ENABLE_AUDIT_LOGGING: false
    ENABLE_DEFAULT_STORAGE_CLASS: true
    CLUSTER_CIDR: 100.96.0.0/11
    SERVICE_CIDR: 100.64.0.0/13
    NODE_STARTUP_TIMEOUT: 20m
    CONTROL_PLANE_MACHINE_COUNT: {{ if eq .Values.cluster_plan "prod" }}3{{ else }}1{{ end }}
    WORKER_MACHINE_COUNT: 1
    WORKER_MACHINE_COUNT_0: 1
    WORKER_MACHINE_COUNT_1: {{ if eq .Values.cluster_plan "prod" }}1{{ else }}null{{ end }}
    WORKER_MACHINE_COUNT_2: {{ if eq .Values.cluster_plan "prod" }}1{{ else }}null{{ end }}
    OS_NAME: ubuntu
    OS_VERSION: 20.04
    OS_ARCH: amd64
    ENABLE_AUTOSCALER: {{ if eq .Values.autoscaling.enabled true }}true{{ else }}false{{ end }}
    AUTOSCALER_MAX_NODES_TOTAL: 15
    AUTOSCALER_SCALE_DOWN_DELAY_AFTER_ADD: 10m
    AUTOSCALER_SCALE_DOWN_DELAY_AFTER_DELETE: 10s
    AUTOSCALER_SCALE_DOWN_DELAY_AFTER_FAILURE: 3m
    AUTOSCALER_SCALE_DOWN_UNNEEDED_TIME: 10m
    AUTOSCALER_MAX_NODE_PROVISION_TIME: 15m
    AUTOSCALER_MIN_SIZE_0: 1
    AUTOSCALER_MAX_SIZE_0: 4
    AUTOSCALER_MIN_SIZE_1: 1
    AUTOSCALER_MAX_SIZE_1: 4
    AUTOSCALER_MIN_SIZE_2: 1
    AUTOSCALER_MAX_SIZE_2: 4
    IDENTITY_MANAGEMENT_TYPE: none
    CERT_DURATION: 2160h
    CERT_RENEW_BEFORE: 360h
    OIDC_IDENTITY_PROVIDER_NAME: ""
    OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
    OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
    OIDC_IDENTITY_PROVIDER_SCOPES: ""
    OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: null
    OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
    SUPERVISOR_ISSUER_URL: null
    SUPERVISOR_ISSUER_CA_BUNDLE_DATA_B64: null
    LDAP_BIND_DN: ""
    LDAP_HOST: ""
    LDAP_USER_SEARCH_BASE_DN: ""
    LDAP_USER_SEARCH_FILTER: ""
    LDAP_USER_SEARCH_USERNAME: userPrincipalName
    LDAP_USER_SEARCH_ID_ATTRIBUTE: DN
    LDAP_USER_SEARCH_EMAIL_ATTRIBUTE: DN
    LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
    LDAP_GROUP_SEARCH_BASE_DN: ""
    LDAP_GROUP_SEARCH_FILTER: ""
    LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
    LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
    LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
    LDAP_ROOT_CA_DATA_B64: ""
    AVI_ENABLE: false
    AVI_NAMESPACE: tkg-system-networking
    AVI_DISABLE_INGRESS_CLASS: true
    AVI_AKO_IMAGE_PULL_POLICY: IfNotPresent
    AVI_ADMIN_CREDENTIAL_NAME: avi-controller-credentials
    AVI_CA_NAME: avi-controller-ca
    AVI_CONTROLLER: null
    AVI_USERNAME: ""
    AVI_CLOUD_NAME: null
    AVI_SERVICE_ENGINE_GROUP: null
    AVI_DATA_NETWORK: null
    AVI_DATA_NETWORK_CIDR: null
    AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: null
    AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: null
    AVI_CA_DATA_B64: ""
    AVI_LABELS: null
    AVI_DISABLE_STATIC_ROUTE_SYNC: true
    AVI_INGRESS_DEFAULT_INGRESS_CONTROLLER: false
    AVI_INGRESS_SHARD_VS_SIZE: ""
    AVI_INGRESS_SERVICE_TYPE: ""
    AVI_INGRESS_NODE_NETWORK_LIST: ""
    AVI_CONTROL_PLANE_HA_PROVIDER: true
    ANTREA_NO_SNAT: false
    ANTREA_TRAFFIC_ENCAP_MODE: encap
    ANTREA_PROXY: true
    ANTREA_ENDPOINTSLICE: true
    ANTREA_POLICY: true
    ANTREA_NODEPORTLOCAL: true
    ANTREA_TRACEFLOW: true
    ANTREA_EGRESS: true
    ANTREA_FLOWEXPORTER: false
    ANTREA_DISABLE_UDP_TUNNEL_OFFLOAD: false
    PROVIDER_TYPE: vsphere
    TKG_CLUSTER_ROLE: workload
    TKG_VERSION: v1.6.0
    CNI: antrea
    VSPHERE_VERSION: 7.0.3
type: addons.cluster.x-k8s.io/resource-set
