---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster_name }}-default-storage-class
  namespace: {{ .Values.cluster_namespace }}
stringData:
  value: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: default
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: csi.vsphere.vmware.com
    allowVolumeExpansion: true
type: addons.cluster.x-k8s.io/resource-set
