---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: cloud-provider/vsphere-cpi
  labels:
    tkg.tanzu.vmware.com/addon-name: vsphere-cpi
    tkg.tanzu.vmware.com/cluster-name: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-vsphere-cpi-addon
  namespace: {{ .Values.cluster_namespace }}
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    vsphereCPI:
      tlsThumbprint: ""
      server: {{ .Values.vsphere.server }}
      datacenter: {{ .Values.vsphere.datacenter }}
      username: {{ .Values.vsphere.username }}
      password: {{ .Values.vsphere.password }}
      region: null
      zone: null
      insecureFlag: {{ .Values.vsphere.insecure }}
      vmExcludeInternalNetworkSubnetCidr: ""
      vmExcludeExternalNetworkSubnetCidr: ""
      cloudProviderExtraArgs:
        tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      nsxt:
        podRoutingEnabled: false
        routes:
          routerPath: ""
          clusterCidr: 100.96.0.0/11
        username: ""
        password: ""
        host: ""
        insecureFlag: "false"
        remoteAuth: "false"
        vmcAccessToken: ""
        vmcAuthHost: ""
        clientCertKeyData: ""
        clientCertData: ""
        rootCAData: ""
        secretName: cloud-provider-vsphere-nsxt-credentials
        secretNamespace: kube-system
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""
type: tkg.tanzu.vmware.com/addon
