---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.cluster_namespace }}
stringData:
  password: {{ .Values.vsphere.password }}
  username: {{ .Values.vsphere.username }}
