---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: metadata/tkg
  name: {{ .Values.cluster_name }}-tkg-metadata-configmap
  namespace: {{ .Values.cluster_namespace }}
stringData:
  value: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: tkg-metadata
      namespace: tkg-system-public
      annotations:
        tkg.tanzu.vmware.com/addon-type: metadata/tkg
    data:
      metadata.yaml: |
        cluster:
          name: {{ .Values.cluster_name }}
          type: workload
          plan: {{ .Values.cluster_plan }}
          kubernetesProvider: VMware Tanzu Kubernetes Grid
          tkgVersion: v1.6.0
          edition: tkg
          infrastructure:
            provider: vsphere
        bom:
          configmapRef:
            name: tkg-bom
type: addons.cluster.x-k8s.io/resource-set
