---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-Secret: external-dns-packages-values
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: external-dns
  namespace: packages
spec:
  serviceAccountName:  tmcsm-gitops-sa
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      constraints: 0.12.2+vmware.5-tkg.1
  values:
  - secretRef:
      name: external-dns-packages-values
