---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: external-dns-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: external-dns-packages-clust
er-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: external-dns-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: external-dns-packages-sa
  name: external-dns
  namespace: packages
spec:
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      constraints: 0.12.2+vmware.5-tkg.1
  serviceAccountName: external-dns-packages-sa
  values:
  - secretRef:
      name: external-dns-packages-values
