---
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: LDAPIdentityProvider
metadata:
  name: tmc-self-managed
  namespace: tmc-local
spec:
  bind:
    secretName: openldap-bind-account
  groupSearch:
    attributes:
      groupName: cn
    base: dc=pinniped,dc=dev
    filter: (objectClass=groupOfUniqueNames)
  host: "openldap.openldap.svc.cluster.local"
  tls:
    certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZzakNDQTVxZ0F3SUJBZ0lVRHZCeGduTHdMWWIvdHhLc3RodC9Eby9ESTFZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1l6RUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdNQ0VOdmJHOXlZV1J2TVE4d0RRWURWUVFIREFaRQpaVzUyWlhJeEREQUtCZ05WQkFvTUEyeGhZakVMTUFrR0ExVUVDd3dDU1ZReEZUQVRCZ05WQkFNTURHMXdiWFJ0ClkyeGhZaTVwYnpBZUZ3MHlNekEzTWpVeU1EVXpNREJhRncwek16QTNNakl5TURVek1EQmFNR014Q3pBSkJnTlYKQkFZVEFsVlRNUkV3RHdZRFZRUUlEQWhEYjJ4dmNtRmtiekVQTUEwR0ExVUVCd3dHUkdWdWRtVnlNUXd3Q2dZRApWUVFLREFOc1lXSXhDekFKQmdOVkJBc01Ba2xVTVJVd0V3WURWUVFEREF4dGNHMTBiV05zWVdJdWFXOHdnZ0lpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRQ29nSEY1anRXcHp3VDh1S1JNNHNyT1BOY2QKM1c1bFVtaFc1Z1pxSnN0c1hnNmhDUlJSUkpCSnZqRldIMCtSZ0NpbUZVZjJTVTFPNHFyVG4vVjZFY0J4MFN5RwpDTU9FWHF4RHJqNG5EbEV1MWllR3RscUxxTmxQd3NwbXFRcmFLd1FydVNPSTBqRkJlcEVJWGFvWDhXSU1jaVFXCmgyYTkraHZKNkJGVjUwck8zaHJIa1R4V2Q5dXlKRVdOVFN0NlA4KzJvMjh4ZWJ1SnFwQmtRenpyR3Nxdm5ONGkKUnQ2SnhNK1R4c1ZXWkJNalljZ0E1R3FwcU9wYUtIQy9mUCt0cFBiT2tJSERUNm40VjFrQmhmcnVNR1pxcGtrVgpwVWkyNWdqRGV3aDJOUjhMVERYWm9reWNRWUdIWStKR2dYNytBTG5ReFpPSE1Nb1IrOE1NUnVoa013MGw0TysxCkFDQjRHazBsRGFtT25PZnFsZUtpdFgza09Vd0FRS1NKWUR2UjJXYTZJdUsxRXV1cjU4VC8vdjBPU2JDcEgzaWoKaHEwa2drd1h6bGg2WGJHVXJDZmQvNjVCMlA1UFFLaWFDbVoxTy95UWpPcSsyckhzL2xhU0NWSVh6WEJWVXdjNApvNWdYT0lyMXVpSUlNTDNreTZjSmZrUXVqQ1VwNkZDamd4aVRTK1hsS0Z1QXQ3R3V3MnJNUEpZNGtpczNDVUpYCmF3S212alVXd1FiTUtqeEs3Zm5ZYkpjZVZqQXJnUHJMT0ZMMzVPL1pMcVE1dUFmc3AvL1hiT0FGL3o5TUJRcjkKVXhwbGtoRktmdWJYZ2FMeEtTbWEyRi9jNGE0Y3RtSitHZThXbSszZit0N2d6MEd2dEQ5NC9DRnV1M0RNN3Z2TgpWejN5RVpocFFFb2t6czBvY3dJREFRQUJvMTR3WERBT0JnTlZIUThCQWY4RUJBTUNBWVl3RWdZRFZSMFRBUUgvCkJBZ3dCZ0VCL3dJQkFUQVhCZ05WSFJFRUVEQU9nZ3h0Y0cxMGJXTnNZV0l1YVc4d0hRWURWUjBPQkJZRUZLc1cKWU5ha2RuaWRYaGVaelQwRXlHb3dBLzR4TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFBOVo1VXFBQVAxTXpJUgo3QlQrWUl4aXphSitjK2lpcExRVEtZMTIzTCszb1Vib0hmSWwrblV6UzNkZzl5NUNKUW5DMUFVbFd4ZlRJY1dOCks0RERyb0s5MGtwQmZrRHhPU2dCQndCMWhUS3pIUFFxUGRxaXVKdW9tWXY5SnJtVCs4eTY1Y2N1dXJKSlpCeHEKNlltcjRwQmtva0ZlZGVwdDFFeVhiOHpHR0JCWlhSOUhVQ0VNK1d6ZjVocjZYSGMxZmdwdzM1ZEpYUGdad2ovcQorSTU5ZGU0MkRpcGNYL0daT0I0SFhLVWpidTZuMjdpaUNCSDZCU1lGdmxleUY3dmZaclFuSFZYVHBIT3FmREt2CjNKK1MvOE5oQmFNMytmWFFXUzRhbTlaYVhoN0duNG1XSFJWaW9xNURWNElnTjdnNmZhSmIrMTVCcGRNdFh3bEEKeTNNejcrR1pyWndCZE84NTN2ek1xek4wWnN0N3BIeEorZTRrK0htbStLbkdrUm8rcnMxQTlUdm1QQVY0ckp2RQphVytHUWwxTVl5OTRSWGZJU001QktCaW8yVUZibEtZbi9zd2VYN0xsQndHT25aWFY2WllNOTh0UEVoZWdoVzBJCmdsUGcwOHJ0blZQRlJMMzRZOENyUnV0TlRlNXJaZjd2WElpRUxLVG1YVXN5R0hpdXFMYlhnUmhzRGVuVmV1TksKajc2UTIvMlpTeERyQ3Q3aWtwWWg4NTFrM1ZOeE5vZ3ZhMkVVL3MyaHJyTTE3eGEvcDV6dCtSSE92NmcvcE9KUgpuNlZJT3pSMTFqbUFrODNJcldPeWluZytMUVd1Tzl6N1VJTzM2MzBFQ1RnelNGeUVyQTc1T3VNT3RwVUNvWDhNCk4rbFN3bFpVLzFQQnhwMHNnMXdNRmhtZnAzL1M5Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  userSearch:
    attributes:
      uid: cn
      username: cn
    base: dc=pinniped,dc=dev
    filter: (objectClass=inetOrgPerson)
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-bind-account
  namespace: tmc-local
type: kubernetes.io/basic-auth
stringData:
  username: "cn=admin,dc=pinniped,dc=dev"
  password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-overlay-secret
  namespace: tmc-local
stringData:
  patch.yaml: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:overlay", "overlay")
    ---
    #@overlay/match missing_ok=True,by=overlay.subset({"kind":"OIDCIdentityProvider", "metadata": {"name": "pinniped-upstream"}})
    ---
    #@overlay/remove
    apiVersion:
    #@overlay/remove
    kind:
    #@overlay/remove
    metadata:
    #@overlay/remove
    spec:
---
apiVersion: v1
kind: Secret
metadata:
  name: tmc-overlay-override
  namespace: tmc-local
stringData:
  patch-oidc.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"PackageInstall", "metadata": {"name": "tmc-local-stack"}})
    ---
    metadata:
      annotations:
        #@overlay/match missing_ok=True
        ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: ldap-overlay-secret#@ load("@ytt:data", "data")
