---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: metadata/tkg
  name: {{ .Values.cluster_name }}-tkg-metadata-namespace-role
  namespace: {{ .Values.cluster_namespace }}
stringData:
  value: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: tkg-system-public
      annotations:
        tkg.tanzu.vmware.com/addon-type: metadata/tkg
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: tkg-metadata-reader
      namespace: tkg-system-public
      annotations:
        tkg.tanzu.vmware.com/addon-type: metadata/tkg
    rules:
    - apiGroups:
      - ""
      resourceNames:
      - tkg-metadata
      - tkg-bom
      resources:
      - configmaps
      verbs:
      - get
      - list
      - watch
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: tkg-metadata-reader
      namespace: tkg-system-public
      annotations:
        tkg.tanzu.vmware.com/addon-type: metadata/tkg
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: tkg-metadata-reader
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:authenticated
type: addons.cluster.x-k8s.io/resource-set
