---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: addons-management/core-package-repo
  name: {{ .Values.cluster_name }}-core-package-repository-crs
  namespace: {{ .Values.cluster_namespace }}
stringData:
  value: |
    apiVersion: packaging.carvel.dev/v1alpha1
    kind: PackageRepository
    metadata:
      name: tanzu-core
      namespace: tkg-system
      annotations:
        tkg.tanzu.vmware.com/addon-type: addons-management/core-package-repo
    spec:
      fetch:
        imgpkgBundle:
          image: {{ .Values.imageRepository }}/packages/core/repo:v1.23.8_vmware.2-tkg.1
type: addons.cluster.x-k8s.io/resource-set
