---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  annotations:
    vmTemplateMoid: vm-45
  name: {{ .Values.cluster_name }}-control-plane
  namespace: {{ .Values.cluster_namespace }}
spec:
  template:
    spec:
      cloneMode: fullClone
      datacenter: {{ .Values.vsphere.datacenter }}
      datastore: {{ .Values.vsphere.datastore }}
      diskGiB: {{ .Values.control_plane.diskGiB }}
      folder: {{ .Values.vsphere.folder }}
      memoryMiB: {{ .Values.control_plane.memoryMiB }}
      network:
        devices:
        - dhcp4: true
          networkName: {{ .Values.vsphere.networkName }}
      numCPUs: {{ .Values.control_plane.numCPUs }}
      resourcePool: {{ .Values.vsphere.resourcePool }}
      server: {{ .Values.vsphere.server }}
      storagePolicyName: ""
      template: {{ .Values.vsphere.template }}
