---
apiVersion: v1
stringData:
  external-dns-default-values.yaml: |
    ---
    namespace: tanzu-system-service-discovery
    deployment:
      args:
        - --source=service
        - --source=ingress
        - --source=contour-httpproxy
        - --domain-filter=mpmtmclab.io
        - --policy=upsert-only
        - --registry=txt
        - --txt-prefix=externaldns-
        - --provider=azure-private-dns
        - --azure-resource-group=tools
      env: []
      securityContext: {}
      volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
        - name: azure-config-file
          secret:
            secretName: azure-config-file
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: external-dns-packages
  name: external-dns-packages-values
  namespace: packages
type: Opaque
