---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: tmcsm-gitops-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: tmcsm-gitops-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tmcsm-gitops-sa
  namespace: packages
