---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: fluxcd-kustomize-controller
  namespace: packages
spec:
  serviceAccountName: tmcsm-gitops-sa
  packageRef:
    refName: fluxcd-kustomize-controller.tanzu.vmware.com
    versionSelection:
      constraints: 0.32.0+vmware.1-tkg.1
