apiVersion: v1
kind: Secret
metadata:
  name: tanzu-mission-control-packages-values
  namespace: tmc-local
data:
  values.yaml: aGFyYm9yUHJvamVjdDogaGFyYm9yLm1wbXRtY2xhYi5pby90bWMKZG5zWm9uZTogdG1jLm1wbXRtY2xhYi5pbwpjbHVzdGVySXNzdWVyOiBsb2NhbC1pc3N1ZXIKcG9zdGdyZXM6CiAgdXNlclBhc3N3b3JkOiBQYXNzdzByZAogIG1heENvbm5lY3Rpb25zOiAzMDAKbWluaW86CiAgdXNlcm5hbWU6IHJvb3QKICBwYXNzd29yZDogUGFzc3cwcmQKY29udG91ckVudm95OgogIHNlcnZpY2VUeXBlOiBMb2FkQmFsYW5jZXIKICBzZXJ2aWNlQW5ub3RhdGlvbnM6CiAgICBzZXJ2aWNlLmJldGEua3ViZXJuZXRlcy5pby9henVyZS1sb2FkLWJhbGFuY2VyLWludGVybmFsOiAidHJ1ZSIKYWxlcnRtYW5hZ2VyOgogIGNyaXRpY2FsQWxlcnRSZWNlaXZlcjoge30KICB3YXJuaW5nQWxlcnRSZWNlaXZlcjoge30Kb2lkYzoKICBpc3N1ZXJUeXBlOiBwaW5uaXBlZAogIGlzc3VlclVSTDogaHR0cHM6Ly9hc2QKICBjbGllbnRJRDogYXNkCiAgY2xpZW50U2VjcmV0OiBhc2QKcGlubmlwZWRFeHRyYUVudlZhcnM6Ci0gbmFtZTogdGVzdAogIHZhbHVlOiB0ZXN0CnRlbGVtZXRyeToKICBjZWlwT3B0SW46IHRydWUKICBlYW5OdW1iZXI6IGVhbi1ub3Qtc3BlY2lmaWVkCiAgY2VpcEFncmVlbWVudDogdHJ1ZQp0cnVzdGVkQ0FzOgogIGN1c3RvbS1jYS5wZW06IHwKICAgIC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQogICAgTUlJRnNqQ0NBNXFnQXdJQkFnSVVEdkJ4Z25Md0xZYi90eEtzdGh0L0RvL0RJMVl3RFFZSktvWklodmNOQVFFTAogICAgQlFBd1l6RUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdNQ0VOdmJHOXlZV1J2TVE4d0RRWURWUVFIREFaRQogICAgWlc1MlpYSXhEREFLQmdOVkJBb01BMnhoWWpFTE1Ba0dBMVVFQ3d3Q1NWUXhGVEFUQmdOVkJBTU1ERzF3YlhSdAogICAgWTJ4aFlpNXBiekFlRncweU16QTNNalV5TURVek1EQmFGdzB6TXpBM01qSXlNRFV6TURCYU1HTXhDekFKQmdOVgogICAgQkFZVEFsVlRNUkV3RHdZRFZRUUlEQWhEYjJ4dmNtRmtiekVQTUEwR0ExVUVCd3dHUkdWdWRtVnlNUXd3Q2dZRAogICAgVlFRS0RBTnNZV0l4Q3pBSkJnTlZCQXNNQWtsVU1SVXdFd1lEVlFRRERBeHRjRzEwYldOc1lXSXVhVzh3Z2dJaQogICAgTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDb2dIRjVqdFdwendUOHVLUk00c3JPUE5jZAogICAgM1c1bFVtaFc1Z1pxSnN0c1hnNmhDUlJSUkpCSnZqRldIMCtSZ0NpbUZVZjJTVTFPNHFyVG4vVjZFY0J4MFN5RwogICAgQ01PRVhxeERyajRuRGxFdTFpZUd0bHFMcU5sUHdzcG1xUXJhS3dRcnVTT0kwakZCZXBFSVhhb1g4V0lNY2lRVwogICAgaDJhOStodko2QkZWNTByTzNockhrVHhXZDl1eUpFV05UU3Q2UDgrMm8yOHhlYnVKcXBCa1F6enJHc3F2bk40aQogICAgUnQ2SnhNK1R4c1ZXWkJNalljZ0E1R3FwcU9wYUtIQy9mUCt0cFBiT2tJSERUNm40VjFrQmhmcnVNR1pxcGtrVgogICAgcFVpMjVnakRld2gyTlI4TFREWFpva3ljUVlHSFkrSkdnWDcrQUxuUXhaT0hNTW9SKzhNTVJ1aGtNdzBsNE8rMQogICAgQUNCNEdrMGxEYW1Pbk9mcWxlS2l0WDNrT1V3QVFLU0pZRHZSMldhNkl1SzFFdXVyNThULy92ME9TYkNwSDNpagogICAgaHEwa2drd1h6bGg2WGJHVXJDZmQvNjVCMlA1UFFLaWFDbVoxTy95UWpPcSsyckhzL2xhU0NWSVh6WEJWVXdjNAogICAgbzVnWE9JcjF1aUlJTUwza3k2Y0pma1F1akNVcDZGQ2pneGlUUytYbEtGdUF0N0d1dzJyTVBKWTRraXMzQ1VKWAogICAgYXdLbXZqVVd3UWJNS2p4SzdmblliSmNlVmpBcmdQckxPRkwzNU8vWkxxUTV1QWZzcC8vWGJPQUYvejlNQlFyOQogICAgVXhwbGtoRktmdWJYZ2FMeEtTbWEyRi9jNGE0Y3RtSitHZThXbSszZit0N2d6MEd2dEQ5NC9DRnV1M0RNN3Z2TgogICAgVnozeUVaaHBRRW9renMwb2N3SURBUUFCbzE0d1hEQU9CZ05WSFE4QkFmOEVCQU1DQVlZd0VnWURWUjBUQVFILwogICAgQkFnd0JnRUIvd0lCQVRBWEJnTlZIUkVFRURBT2dneHRjRzEwYldOc1lXSXVhVzh3SFFZRFZSME9CQllFRktzVwogICAgWU5ha2RuaWRYaGVaelQwRXlHb3dBLzR4TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFBOVo1VXFBQVAxTXpJUgogICAgN0JUK1lJeGl6YUorYytpaXBMUVRLWTEyM0wrM29VYm9IZklsK25VelMzZGc5eTVDSlFuQzFBVWxXeGZUSWNXTgogICAgSzRERHJvSzkwa3BCZmtEeE9TZ0JCd0IxaFRLekhQUXFQZHFpdUp1b21ZdjlKcm1UKzh5NjVjY3V1ckpKWkJ4cQogICAgNlltcjRwQmtva0ZlZGVwdDFFeVhiOHpHR0JCWlhSOUhVQ0VNK1d6ZjVocjZYSGMxZmdwdzM1ZEpYUGdad2ovcQogICAgK0k1OWRlNDJEaXBjWC9HWk9CNEhYS1VqYnU2bjI3aWlDQkg2QlNZRnZsZXlGN3ZmWnJRbkhWWFRwSE9xZkRLdgogICAgM0orUy84TmhCYU0zK2ZYUVdTNGFtOVphWGg3R240bVdIUlZpb3E1RFY0SWdON2c2ZmFKYisxNUJwZE10WHdsQQogICAgeTNNejcrR1pyWndCZE84NTN2ek1xek4wWnN0N3BIeEorZTRrK0htbStLbkdrUm8rcnMxQTlUdm1QQVY0ckp2RQogICAgYVcrR1FsMU1ZeTk0UlhmSVNNNUJLQmlvMlVGYmxLWW4vc3dlWDdMbEJ3R09uWlhWNlpZTTk4dFBFaGVnaFcwSQogICAgZ2xQZzA4cnRuVlBGUkwzNFk4Q3JSdXROVGU1clpmN3ZYSWlFTEtUbVhVc3lHSGl1cUxiWGdSaHNEZW5WZXVOSwogICAgajc2UTIvMlpTeERyQ3Q3aWtwWWg4NTFrM1ZOeE5vZ3ZhMkVVL3MyaHJyTTE3eGEvcDV6dCtSSE92NmcvcE9KUgogICAgbjZWSU96UjExam1BazgzSXJXT3lpbmcrTFFXdU85ejdVSU8zNjMwRUNUZ3pTRnlFckE3NU91TU90cFVDb1g4TQogICAgTitsU3dsWlUvMVBCeHAwc2cxd01GaG1mcDMvUzlnPT0KICAgIC0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: tanzu-mission-control-packages
    kapp.k14s.io/update-strategy: fallback-on-replace
  name: tanzu-mission-control-packages-sa
  namespace: tmc-local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: tanzu-mission-control-packages
    kapp.k14s.io/update-strategy: fallback-on-replace
  name: tanzu-mission-control-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: tanzu-mission-control-packages
    kapp.k14s.io/update-strategy: fallback-on-replace
  name: tanzu-mission-control-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-mission-control-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: tanzu-mission-control-packages-sa
  namespace: tmc-local
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: tanzu-mission-control-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: tanzu-mission-control-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: tanzu-mission-control-packages-sa
    kapp.k14s.io/update-strategy: fallback-on-replace
    kapp.k14s.io/create-strategy: fallback-on-replace
  name: tanzu-mission-control
  namespace: tmc-local
spec:
  serviceAccountName: tanzu-mission-control-packages-sa
  packageRef:
    refName: tmc.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0
  values:
  - secretRef:
      name: tanzu-mission-control-packages-values
