---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: addons-management/standard-package-repo
  name: {{ .Values.cluster_name }}-standard-package-repository-crs
  namespace: {{ .Values.cluster_namespace }}
stringData:
  value: |
    apiVersion: packaging.carvel.dev/v1alpha1
    kind: PackageRepository
    metadata:
      name: tanzu-standard
      namespace: tanzu-package-repo-global
      annotations:
        tkg.tanzu.vmware.com/addon-type: addons-management/standard-package-repo
        tanzu.vmware.com/owner: tkg
    spec:
      fetch:
        imgpkgBundle:
          image: {{ .Values.imageRepository }}/packages/standard/repo:v1.6.0
type: addons.cluster.x-k8s.io/resource-set
