---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: cni/antrea
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    tkg.tanzu.vmware.com/addon-name: antrea
    tkg.tanzu.vmware.com/cluster-name: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-antrea-addon
  namespace: {{ .Values.cluster_namespace }}
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    infraProvider: vsphere
    antrea:
      config:
        egress:
          exceptCIDRs: []
        nodePortLocal:
          enabled: true
          portRange: 61000-62000
        antreaProxy:
          proxyAll: false
          nodePortAddresses: []
          skipServices: []
          proxyLoadBalancerIPs: false
        flowExporter:
          collectorAddress: flow-aggregator.flow-aggregator.svc:4739:tls
          pollInterval: 5s
          activeFlowTimeout: 30s
          idleFlowTimeout: 15s
        kubeAPIServerOverride: null
        transportInterface: null
        transportInterfaceCIDRs: []
        multicastInterfaces: []
        tunnelType: geneve
        trafficEncryptionMode: none
        enableUsageReporting: false
        wireGuard:
          port: 51820
        serviceCIDR: 100.64.0.0/13
        trafficEncapMode: encap
        noSNAT: false
        tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
        disableUdpTunnelOffload: false
        featureGates:
          AntreaProxy: true
          EndpointSlice: true
          AntreaPolicy: true
          AntreaTraceflow: true
          NodePortLocal: true
          NetworkPolicyStats: false
          Egress: true
          AntreaIPAM: false
          FlowExporter: false
          ServiceExternalIP: false
          Multicast: false
      image:
        repository: {{ .Values.imageRepository }}
        path: antrea-advanced-debian
        tag: v1.5.3
        pullPolicy: IfNotPresent
type: tkg.tanzu.vmware.com/addon
