---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: csi/vsphere-csi
  labels:
    tkg.tanzu.vmware.com/addon-name: vsphere-csi
    tkg.tanzu.vmware.com/cluster-name: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-vsphere-csi-addon
  namespace: {{ .Values.cluster_namespace }}
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    vsphereCSI:
      CSIAttacherImage:
        repository: {{ .Values.imageRepository }}
        path: csi/csi-attacher
        tag: v3.3.0_vmware.1
        pullPolicy: IfNotPresent
      vsphereCSIControllerImage:
        repository: {{ .Values.imageRepository }}
        path: csi/vsphere-block-csi-driver
        tag: v2.5.2_vmware.1
        pullPolicy: IfNotPresent
      livenessProbeImage:
        repository: {{ .Values.imageRepository }}
        path: csi/csi-livenessprobe
        tag: v2.4.0_vmware.1
        pullPolicy: IfNotPresent
      vsphereSyncerImage:
        repository: {{ .Values.imageRepository }}
        path: csi/volume-metadata-syncer
        tag: v2.5.2_vmware.1
        pullPolicy: IfNotPresent
      CSIProvisionerImage:
        repository: {{ .Values.imageRepository }}
        path: csi/csi-provisioner
        tag: v3.0.0_vmware.1
        pullPolicy: IfNotPresent
      CSINodeDriverRegistrarImage:
        repository: {{ .Values.imageRepository }}
        path: csi/csi-node-driver-registrar
        tag: v2.3.0_vmware.1
        pullPolicy: IfNotPresent
      namespace: kube-system
      clusterName: {{ .Values.cluster_name }}
      tlsThumbprint: ""
      server: {{ .Values.vsphere.server }}
      datacenter: {{ .Values.vsphere.datacenter }}
      publicNetwork: {{ .Values.vsphere.networkName }}
      username: {{ .Values.vsphere.username }}
      password: {{ .Values.vsphere.password }}
      region: null
      zone: null
      insecureFlag: {{ .Values.vsphere.insecure }}
      vSphereVersion: 7.0.3
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""
      useTopologyCategories: true
      deployment_replicas: {{ if eq .Values.cluster_plan "prod" }}3{{ else }}1{{ end }}
type: tkg.tanzu.vmware.com/addon
