---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: addons-management/secretgen-controller
  labels:
    tkg.tanzu.vmware.com/addon-name: secretgen-controller
    tkg.tanzu.vmware.com/cluster-name: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-secretgen-controller-addon
  namespace: {{ .Values.cluster_namespace }}
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    secretgenController:
      namespace: tanzu-system
      createNamespace: true
type: tkg.tanzu.vmware.com/addon
